# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6e01d2704b317c19d51d7cd83793d3e3eac32ee9c1379915f4606d1b29b437860b7c0bd027e43bb35f278d1c85d3243499d2ea71d1aab16da2263cbb78464d2

test:
  secret_key_base: 651cac403f270edabb0a13701b0ba39eaf3fb0d0df0616a5f6c97fc015ffc993589c13a7a5b5a72de5c6a26dbb7f4cc2fda58a8fbf1144c92590c29f33a022c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
