# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 796668b7194a7376aed9173447414b727f8a73d7611e6878580441408c7f34e92ad1b8f27840ae4a97a02d855d037debc42ed05aa57014ea156db9d3e2ad88d8

test:
  secret_key_base: 45957ee791813f5fa5356f0320f89f146d0c4e63ba0bf40f2b6dc300b1a7bd2d8b96bac5d989b4044f786a17aa6b90f315731471889bdfe418dd24999106c135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
